#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <time.h>
#include <sys/wait.h>

extern char **environ;
// Feel free to change the data structures generated by AI.

#define MAX_SYSCALLS 1024
#define TOP_N 5

typedef struct {
    char name[64];
    double time;
} syscall_stat;

typedef struct {
    syscall_stat stats[MAX_SYSCALLS];
    int count;
    double total_time;
} syscall_stats;

int parse_strace_line(char *line, char *syscall_name, double *time) {
    char *start = strchr(line, '<');
    if(!start) return 0;
    char *end = strchr(line, '>');
    if(!end) return 0;

    char buf[64];
    int len = end - start - 1;
    if (len <=0 || len >= sizeof(buf)) return 0;
    strncpy(buf, start+1, len);
    buf[len] = '\0';
    *time = atof(buf);

    char *p = strchr(line, '(');
    if (p && p>line){
        int name_len = p - line;
        if(name_len >=64) return 0;
        strncpy(syscall_name, line, name_len);
        syscall_name[name_len] = '\0';
        return 1;
    }
    return 0;
}

void add_syscall(syscall_stats *stats, const char *name, double time) {
    for(int i =0 ;i< stats->count ; i++){
        if(strcmp(stats->stats[i].name, name) == 0){
            stats->stats[i].time += time;
            stats->total_time += time;
            return;
        }
    }
    //新增
    if(stats->count < MAX_SYSCALLS){
        strcpy(stats->stats[stats->count].name, name);
        stats->stats[stats->count].time = time;
        stats->count++;
        stats->total_time += time;
        return;
    }
    return;
}
int cmp(const void *a, const void *b){
    syscall_stat *sa = (syscall_stat *)a;
    syscall_stat *sb = (syscall_stat *)b;
    return sb->time - sa->time;
}
void print_top_syscalls(syscall_stats *stats, int n) {
    if(stats->total_time == 0){
        return;
    }
    qsort(stats->stats, stats->count, sizeof(syscall_stat), cmp);
    int print_n = (n < stats->count) ? n : stats->count;
    for(int i=0;i<print_n;i++){
        double pct = (stats->stats[i].time / stats->total_time) * 100;
        printf("%s (%.0f%%)\n", stats->stats[i].name, pct);
    }
    for(int i = 0 ;i<80 ; i++){
        putchar('\0');
    }
    printf(" ========== \n");
}

int main(int argc, char *argv[]) {
    if(argc < 2){
        perror("缺少参数");
        exit(EXIT_FAILURE);
        return -1;
    }
    //处理参数
    char **args = malloc((argc+3) * sizeof(char*)); // strace -T cmd args NULL
    args[0] = "strace";
    args[1] = "-T";
    for(int i=1; i<argc ; i++){
        args[i+1] = argv[i];
    }
    args[argc+1] = NULL;
    int fd[2];
    pipe(fd);
    pid_t pid = fork();
    if(pid == 0){
        //子进程
        close(fd[0]);
        dup2(fd[1], STDOUT_FILENO);
        dup2(fd[1], STDERR_FILENO);
        close(fd[1]);
        execve("/usr/bin/strace", args, environ);
        _exit(1);
    }else{
        close(fd[1]);
        FILE *f;      
        f = fdopen(fd[0],"r");
        char line[256];
        syscall_stats stats = {0};
        struct timespec last = {0}, now;
        while (fgets(line, sizeof(line), f)) {
            char name[64];
            double t;
            if(parse_strace_line(line, name, &t)){
                add_syscall(&stats, name, t);
            }
            clock_gettime(CLOCK_MONOTONIC, &now);

            double diff_ms = (now.tv_sec - last.tv_sec) * 1000 + (now.tv_nsec - last.tv_nsec) / 1000000;
            if (diff_ms >= 100) {
                print_top_syscalls(&stats, TOP_N);
                fflush(stdout);
                last = now;
            } 

        }

    }
    waitpid(pid, NULL, 0);
    return 0;
}
